<?php

namespace ShowcaseBundle\Repository;

/**
 * OrderFormsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderFormsRepository extends \Doctrine\ORM\EntityRepository
{
}
