<?php

namespace ShowcaseBundle\Repository;

/**
 * OrderFormItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderFormItemRepository extends \Doctrine\ORM\EntityRepository
{
}
