<?php

namespace ShowcaseBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderFormRepository extends \Doctrine\ORM\EntityRepository
{
}
